version: '3.8'
services:
 
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    links:
      - postgres:postgres
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file:
      - .env
    networks:
      - postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - .:/app   
    env_file:
      - .env
    networks:
      - postgres


volumes:
  postgres:
    name: nest-prisma-docker-db
  pgadmin_data:

networks:
  postgres:
    driver: bridge
